apiVersion: v1
kind: Service
metadata:
  name: mia-app
spec:
  type: NodePort
  selector:
    app: mia-app
  ports:
    - port: 80
      targetPort: http                 # il nome della porta del container: 8000
      nodePort: 30083                  # http://localhost:30083
